### ISSUE TITLE
PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR

### ISSUE THREAD

**Issue by FelixVincent99** [chill117/express-mysql-session#110]
Can someone help me with this:
```
{
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```

```js
function handleDisconnect() {
    connection = mysql.createConnection(db_config); 
    connection.connect(function(err) {           
      if(err) { 
        console.log('error when connecting to db:', err);
        setTimeout(handleDisconnect, 2000); 
      }
      console.log("Database Connected!");
    });
    connection.on('error', function(err) {
      console.log('db error', err);
      if(err.code === 'PROTOCOL_CONNECTION_LOST') { 
        handleDisconnect();                         
      } else {  
        throw err;
      }
    });
  }
 
  handleDisconnect();
```

**Comment by chill117** [comment]
> You may lose the connection to a MySQL server due to network problems, the server timing you out, the server being restarted, or crashing. All of these events are considered fatal errors, and will have the err.code = 'PROTOCOL_CONNECTION_LOST'. See the Error Handling section for more information.

> Re-connecting a connection is done by establishing a new connection. Once terminated, an existing connection object cannot be re-connected by design.

Using a connection object after a fatal error will result in the error that you are experiencing. You should not try to manually reconnect a connection object that has been disconnected or resulted in a fatal error.

I suggest that you use pooling instead of a single connection. Specifically because:

> With Pool, disconnected connections will be removed from the pool freeing up space for a new connection to be created on the next getConnection call.

See [Server disconnects](https://github.com/mysqljs/mysql#server-disconnects) and [Pooling connections](https://github.com/mysqljs/mysql#pooling-connections) for more information.
