### ISSUE TITLE
Should be possible to set just options.schema.tableName (without columnNames)

### ISSUE THREAD

**Issue by krisdahl** [chill117/express-mysql-session#28]
Basically if you have options set with tableName but not columnName like so:

```
schema: {
  tableName: 'sessions'
}
```

You're required to also set options.schema.columnNames because the default values aren't set.  Probably should use the default values still for columnNames even if tableName is specified.

Or should kick back an cb(error)

Throws this currently:

```
TypeError: Cannot read property 'session_id' of undefined
     at /foo/node/node_modules/express-mysql-session/lib/index.js:109:35
     at fs.js:272:14
     at Object.oncomplete (fs.js:108:15)
```

I may swing back and fix this and do a pull request later.

**Comment by chill117** [comment]
Yes, you're right. The `schema` option should be more flexible, so that if any of the attributes of `schema` are left out, they would be filled with their default values instead.

If you'd like to make a PR for this, let me know here. Otherwise, sometime in the next week or two, I'll look at fixing this.

**Comment by krisdahl** [comment]
Okay will do.  Thanks.
