### ISSUE TITLE
Handling DB disconnects

### ISSUE THREAD

**Issue by aybmab** [chill117/express-mysql-session#37]
Does this module handle DB disconnects?

I'm current'y trying to figure out a bug I get when pushing my project to heroku. Not sure if express-mysql-session is causing it, but I get the following error in my console:

```events.js:154
     throw er; // Unhandled 'error' event
     ^

Error: Connection lost: The server closed the connection.
   at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
   at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:102:28)
   at emitNone (events.js:85:20)
   at Socket.emit (events.js:179:7)
   at endReadableNT (_stream_readable.js:913:12)
   at _combinedTickCallback (node.js:377:13)
   at process._tickCallback (node.js:401:11)
Program node --harmony ./index.js exited with code 1
Starting child process with 'node --harmony ./index.js
```

I assume the connection is lost and needs to be reset, but I'm not sure if the express-mysql-session has a way to handle this. Or is there a way to feed it a pool rather than a connection?

Thanks in advance!

**Comment by chill117** [comment]
If you do not pass an existing MySQL connection to this module, then it uses [mysql-connection-manager](https://github.com/chill117/mysql-connection-manager) to create and manage a MySQL connection (or pool) for you. Options passed to the express-mysql-session module are passed thru to the mysql-connection-manager module; see list of available options [here](https://github.com/chill117/mysql-connection-manager#options). Default values are used for options that are not provided. The default behavior is to attempt to auto-reconnect when a connection has been lost.

**Comment by aybmab** [comment]
Thanks for the quick response! 

Is it possible to pass a database url rather than user, password and database?

**Comment by aybmab** [comment]
@chill117 Or is it possible to pass a pool to express-mysql-session rather than a connection?

Thanks again!

**Comment by chill117** [comment]
> is it possible to pass a pool to express-mysql-session rather than a 
connection?

Yes. There is an example for this use-case in the readme file 
[here](https://github.com/chill117/express-mysql-session#with-an-existing-mysql-connection). 
Instead of using the `mysql.createConnection`, you would use 
`mysql.createPool` to create a connection pool instance.

 > Is it possible to pass a database url rather than user, password and 
database?

Yes. The options you pass the to MySQLStore() constructor as passed thru 
to the 
[node-mysql](https://github.com/felixge/node-mysql#connection-options) 
module when creating a database connection. By default, 
`mysql.createConnection` is used to create a connection object. If you 
want to use connection pooling instead, set the `useConnectionPooling` 
equal to `true`.


References:
* [node-mysql](https://github.com/felixge/node-mysql)
* 
[mysql-connection-manager](https://github.com/chill117/mysql-connection-manager)

**Comment by chill117** [comment]
> is it possible to pass a pool to express-mysql-session rather than a connection?

Yes. There is an example for this use-case in the readme file [here](https://github.com/chill117/express-mysql-session#with-an-existing-mysql-connection). Instead of using the `mysql.createConnection`, you would use `mysql.createPool` to create a connection pool instance.

> Is it possible to pass a database url rather than user, password and database?

Yes. The options you pass the to MySQLStore() constructor as passed thru to the [node-mysql](https://github.com/felixge/node-mysql#connection-options) module when creating a database connection. By default, `mysql.createConnection` is used to create a connection object. If you want to use connection pooling instead, set the `useConnectionPooling` equal to `true`.

References:
* [node-mysql](https://github.com/felixge/node-mysql)
* [mysql-connection-manager](https://github.com/chill117/mysql-connection-manager)

**Comment by aybmab** [comment]
@chill117 The thing is, when using a uri, the node-mysql module just takes a string, rather than an object.

As taken from their docs:

> In addition to passing these options as an object, you can also use a url string. For example:
```
var connection = mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');
```

If we try that with your module, it wont work. Perhaps we could add an option dburi that if will ignore the other options?

**Comment by aybmab** [comment]
It's not really a big deal...I just broke the url down into the components.

**Comment by chill117** [comment]
This could be something to investigate and implement maybe. But I wonder if it's really worth it. As you said, it's possible to just split the connection string into an object and provide that.
