### ISSUE TITLE
Mysql Error logging with an option while creating session store without DEBUG=express-mysql-session*

### ISSUE THREAD

**Issue by rohithramachandran** [chill117/express-mysql-session#59]
When i deployed the project with pm2 sometimes user session getting terminated suddenly due to connection issues is mysql but i am not getting  any messages in console.Is it possible to debug messages from script  to console when some mysql connection issue happens by giving some options while creating store ?

**Comment by chill117** [comment]
All the session methods include a callback argument that will provide an error to the callee. I am not sure what the [express-session module](https://github.com/expressjs/session) does in the event of an error when getting the data for a particular session.

Are you sure that sessions are being destroyed because of the connection issues? Have you been able to reliably reproduce the issue in an isolated environment?

**Comment by rohithramachandran** [comment]
In my local setup it works fine.But in the production server this problem in happening..So if I will investigate more and will reopen this in case i found any issue
